#!/usr/bin/env bash
# Pull the latest aldutex revision into the submodule and rebuild fluxtex.
# Safe to run repeatedly — discards any local modifications inside
# vendor/aldutex (test artifacts like debug_output.pdf) and fast-forwards
# the submodule branch to origin/main.
# Usage: ./update-aldutex.sh
set -euo pipefail

cd "$(dirname "$0")"
REPO_ROOT="$(pwd)"
SUBMODULE="vendor/aldutex"

if [[ ! -e "$SUBMODULE/.git" ]]; then
    echo "==> Initializing aldutex submodule (first run)"
    git submodule update --init --recursive "$SUBMODULE"
fi

cd "$SUBMODULE"

echo "==> Fetching latest aldutex from origin"
git fetch --quiet origin

# Drop any uncommitted modifications inside the submodule before moving
# the branch forward — these are typically test outputs (debug_output.pdf)
# regenerated by cargo test, not user work.
if ! git diff --quiet HEAD --; then
    echo "==> Discarding local modifications in $SUBMODULE"
    git --no-pager diff --name-only HEAD | sed 's/^/    /'
    git checkout --quiet -- .
fi

PREV_SHA="$(git rev-parse --short HEAD)"
# Reset the local main branch to origin/main so we are always
# on the canonical branch and can be fast-forwarded next time.
git checkout --quiet -B main origin/main
NEW_SHA="$(git rev-parse --short HEAD)"

if [[ "$PREV_SHA" == "$NEW_SHA" ]]; then
    echo "==> aldutex already at $NEW_SHA — nothing to pull."
else
    echo "==> aldutex: $PREV_SHA -> $NEW_SHA"
    git --no-pager log --oneline "$PREV_SHA..$NEW_SHA"
fi

cd "$REPO_ROOT"
echo "==> Building fluxtex-app against the updated aldutex"
cargo build -p fluxtex-app

cat <<'NEXT'

==> Done. Launch the app:
    cargo run -p fluxtex-app

When the new aldutex revision works as expected, bump the pinned
submodule pointer with:
    git add vendor/aldutex && git commit -m "bump aldutex submodule"
NEXT
